apiVersion: apps/v1
kind: Deployment
metadata:
  name: nftsvc-deployment
  labels:
    app: nftsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nftsvc
  template:
    metadata:
      labels:
        app: nftsvc
    spec:
      containers:
        - name: nftsvc
          image: i6o6i/emsvc:latest
          ports:
            - containerPort: 8080
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: emsvc-secret
                  key: api-key
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-url
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-database
            - name: REDIS_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-url
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
---
apiVersion: v1
kind: Service
metadata:
  name: nft-service
spec:
  type: NodePort
  selector:
    app: nftsvc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
