// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Microservice/ent/predicate"
	"Microservice/ent/transaction"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tu *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetFrom sets the "from" field.
func (tu *TransactionUpdate) SetFrom(s string) *TransactionUpdate {
	tu.mutation.SetFrom(s)
	return tu
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableFrom(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetFrom(*s)
	}
	return tu
}

// SetTo sets the "to" field.
func (tu *TransactionUpdate) SetTo(s string) *TransactionUpdate {
	tu.mutation.SetTo(s)
	return tu
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableTo(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetTo(*s)
	}
	return tu
}

// SetTokenId sets the "tokenId" field.
func (tu *TransactionUpdate) SetTokenId(u uint64) *TransactionUpdate {
	tu.mutation.ResetTokenId()
	tu.mutation.SetTokenId(u)
	return tu
}

// SetNillableTokenId sets the "tokenId" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableTokenId(u *uint64) *TransactionUpdate {
	if u != nil {
		tu.SetTokenId(*u)
	}
	return tu
}

// AddTokenId adds u to the "tokenId" field.
func (tu *TransactionUpdate) AddTokenId(u int64) *TransactionUpdate {
	tu.mutation.AddTokenId(u)
	return tu
}

// Mutation returns the TransactionMutation object of the builder.
func (tu *TransactionUpdate) Mutation() *TransactionMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TransactionUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TransactionUpdate) check() error {
	if v, ok := tu.mutation.From(); ok {
		if err := transaction.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf(`ent: validator failed for field "Transaction.from": %w`, err)}
		}
	}
	if v, ok := tu.mutation.To(); ok {
		if err := transaction.ToValidator(v); err != nil {
			return &ValidationError{Name: "to", err: fmt.Errorf(`ent: validator failed for field "Transaction.to": %w`, err)}
		}
	}
	if v, ok := tu.mutation.TokenId(); ok {
		if err := transaction.TokenIdValidator(v); err != nil {
			return &ValidationError{Name: "tokenId", err: fmt.Errorf(`ent: validator failed for field "Transaction.tokenId": %w`, err)}
		}
	}
	return nil
}

func (tu *TransactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.From(); ok {
		_spec.SetField(transaction.FieldFrom, field.TypeString, value)
	}
	if value, ok := tu.mutation.To(); ok {
		_spec.SetField(transaction.FieldTo, field.TypeString, value)
	}
	if value, ok := tu.mutation.TokenId(); ok {
		_spec.SetField(transaction.FieldTokenId, field.TypeUint64, value)
	}
	if value, ok := tu.mutation.AddedTokenId(); ok {
		_spec.AddField(transaction.FieldTokenId, field.TypeUint64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetFrom sets the "from" field.
func (tuo *TransactionUpdateOne) SetFrom(s string) *TransactionUpdateOne {
	tuo.mutation.SetFrom(s)
	return tuo
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableFrom(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetFrom(*s)
	}
	return tuo
}

// SetTo sets the "to" field.
func (tuo *TransactionUpdateOne) SetTo(s string) *TransactionUpdateOne {
	tuo.mutation.SetTo(s)
	return tuo
}

// SetNillableTo sets the "to" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableTo(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetTo(*s)
	}
	return tuo
}

// SetTokenId sets the "tokenId" field.
func (tuo *TransactionUpdateOne) SetTokenId(u uint64) *TransactionUpdateOne {
	tuo.mutation.ResetTokenId()
	tuo.mutation.SetTokenId(u)
	return tuo
}

// SetNillableTokenId sets the "tokenId" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableTokenId(u *uint64) *TransactionUpdateOne {
	if u != nil {
		tuo.SetTokenId(*u)
	}
	return tuo
}

// AddTokenId adds u to the "tokenId" field.
func (tuo *TransactionUpdateOne) AddTokenId(u int64) *TransactionUpdateOne {
	tuo.mutation.AddTokenId(u)
	return tuo
}

// Mutation returns the TransactionMutation object of the builder.
func (tuo *TransactionUpdateOne) Mutation() *TransactionMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tuo *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Transaction entity.
func (tuo *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TransactionUpdateOne) check() error {
	if v, ok := tuo.mutation.From(); ok {
		if err := transaction.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf(`ent: validator failed for field "Transaction.from": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.To(); ok {
		if err := transaction.ToValidator(v); err != nil {
			return &ValidationError{Name: "to", err: fmt.Errorf(`ent: validator failed for field "Transaction.to": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.TokenId(); ok {
		if err := transaction.TokenIdValidator(v); err != nil {
			return &ValidationError{Name: "tokenId", err: fmt.Errorf(`ent: validator failed for field "Transaction.tokenId": %w`, err)}
		}
	}
	return nil
}

func (tuo *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.From(); ok {
		_spec.SetField(transaction.FieldFrom, field.TypeString, value)
	}
	if value, ok := tuo.mutation.To(); ok {
		_spec.SetField(transaction.FieldTo, field.TypeString, value)
	}
	if value, ok := tuo.mutation.TokenId(); ok {
		_spec.SetField(transaction.FieldTokenId, field.TypeUint64, value)
	}
	if value, ok := tuo.mutation.AddedTokenId(); ok {
		_spec.AddField(transaction.FieldTokenId, field.TypeUint64, value)
	}
	_node = &Transaction{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
