version: '3.8'

networks:
  redis_cluster_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.100

services:
  redis-master1:
    image: redis/redis-stack:latest
    command: redis-server /data/redis.conf --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip 172.20.0.1 --cluster-announce-port 6379 
    volumes:
      - ./redis-master1:/data
    ports:
      - "6379:6379"
    networks:
      redis_cluster_net:
        ipv4_address: 172.20.0.1


  redis-master2:
    image: redis/redis-stack:latest
    command: redis-server /data/redis.conf --port 6380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip 172.20.0.2 --replica-announce-ip 172.20.0.2 
    volumes:
      - ./redis-master2:/data
    ports:
      - "6380:6380"
    networks:
      redis_cluster_net:
        ipv4_address: 172.20.0.2

  redis-master3:
    image: redis/redis-stack:latest
    command: redis-server /data/redis.conf --port 6381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip 172.20.0.3 --cluster-announce-port 6381
    volumes:
      - ./redis-master3:/data
    ports:
      - "6381:6381"
    networks:
      redis_cluster_net:
        ipv4_address: 172.20.0.3

  redis-replica1:
    image: redis/redis-stack:latest
    command: redis-server /data/redis.conf --port 6382 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --logfile redis-replica1.log --replica-announce-ip 172.20.0.4 --cluster-announce-ip 172.20.0.4 
    volumes:
      - ./redis-replica1:/data
    ports:
      - "6382:6382"
    networks:
      redis_cluster_net:
        ipv4_address: 172.20.0.4

  redis-replica2:
    image: redis/redis-stack:latest
    command: redis-server /data/redis.conf --port 6383 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --replica-announce-ip 172.20.0.5 --cluster-announce-ip 172.20.0.5 
    volumes:
      - ./redis-replica2:/data
    ports:
      - "6383:6383"
    networks:
      redis_cluster_net:
        ipv4_address: 172.20.0.5

  redis-replica3:
    image: redis/redis-stack:latest
    command: redis-server /data/redis.conf --port 6384 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --replica-announce-ip 172.20.0.6 --replica-announce-port 6384 --cluster-announce-ip 172.20.0.6 --cluster-announce-port 6384
    volumes:
      - ./redis-replica3:/data
    ports:
      - "6384:6384"
    networks:
      redis_cluster_net:
        ipv4_address: 172.20.0.6
